CREATE TABLE IF NOT EXISTS Artists (
	id SERIAL PRIMARY KEY,
	name VARCHAR(80) NOT NULL
);

CREATE TABLE IF NOT EXISTS Albums (
	id SERIAL primary key,
	idArtist INTEGER REFERENCES Artists(id),
	title VARCHAR(80) NOT NULL,
	year DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS Tracks (
	id SERIAL PRIMARY KEY,
	idAlbum INTEGER REFERENCES Albums(id),
	name VARCHAR(80) NOT NULL,
	timeDuration TIME NOT NULL
);